print("========================================")
print(" Jenkins + GitHub CI/CD Demo")
print("========================================")
print("Updated source code successfully retrieved from GitHub.")
print("Jenkins executed the latest version from the main branch.")
print("Assignment 6 - DevOps")