pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/SwayamMandhani06/DevOps.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building application...'
                bat 'cd Assignment-6 && "C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\python.exe" app.py'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }
    }
}